SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF;
SELECT * FROM BOARD JOIN BOARD_COMMENT ON BOARD_NO=BOARD_REF JOIN MEMBER ON USERID=BOARD_WRITER WHERE BOARD_NO=50;
SELECT * FROM "MEMBER" WHERE userid='admin2';
SELECT * FROM BOARD;