SELECT * FROM STUDENT;
SELECT STUDENT_NO AS STUDENTNO,
	 		STUDENT_NAME AS STUDENTNAME,
	 		STUDENT_TEL AS STUDENTEL,
	 		STUDENT_EMAIL AS STUDENTEMAIL,
	 		STUDENT_ADDR As STUDENTADDRESS,
	 		REG_DATE
	 	FROM STUDENT WHERE STUDENT_NO=1;